FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# APTD Orders

Polls is a simple API allowing consumers to view polls and vote in them.

## Orders Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json; charset=utf-8)

        [
            {"order": "0001"},
            {"order": "0002"}
        ]